"""Initial migration

Revision ID: 5a940db2ba56
Revises: 
Create Date: 2025-11-24 22:20:09.421010

"""


# revision identifiers, used by Alembic.
revision = '5a940db2ba56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
